### ISSUE TITLE
Docs: Add colab MWA to showcase simplicity, performance, and flexibility.

### ISSUE THREAD

**Issue by mb010** [mb010/Cata2Data#32]
Building on the example in #31, we should probably just make a Colab based example that uses the LOTSS test field to highlight the functionality and give immediate use case to potential users.

**Comment by OllyK** [comment]
I did start looking into this, but it looks like the data download link https://lofar-surveys.org/public/DR2/mosaics/P000+23/mosaic-blanked.fits is borked at present...
