### ISSUE TITLE
Bug: CI Runs Setuptools Not 

### ISSUE THREAD

**Issue by mb010** [mb010/Cata2Data#36]
CI matrix runs failed with 
```shell
      ModuleNotFoundError: No module named 'setuptools.dep_util'
```
potentially related to [this](https://stackoverflow.com/questions/78154502/pythons-setuptools-is-failing-to-install-at-random-in-my-github-actions-workflo). @OllyK any ideas? 

See the logs [here](https://github.com/mb010/Cata2Data/actions/runs/10700172643).

**Comment by OllyK** [comment]
Hi @mb010 . Only seems to be an issue on 3.12. Will take a look and see if I can resolve it. Sorry for all the noise from failed test runs whilst that happens!
